FROM golang:alpine
COPY . /usr/local/go/src/github.com/tentativafc/investing-broker/sts-service/
WORKDIR /usr/local/go/src/github.com/tentativafc/investing-broker/sts-service/
# RUN go get -u -v -f all
# CMD ["go", "run", "main.go"]