export const CHECK_AUTH = 'checkAuth'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const REGISTER = 'register'
export const FORGET_PASSWORD = 'forgetPassword'
export const UPDATE_USER = 'updateUser'
export const SHOW_ERRORS = 'showErrors'
