kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-user-pv
  labels:
    type: local
    app: postgres-user
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/postgres-user"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-user-pv
  labels:
    app: postgres-user
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
