kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-sts-pv
  labels:
    type: local
    app: postgres-sts
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-sts/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-sts-pv-claim
  labels:
    app: postgres-sts
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
