apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: tentativafc/ib-user-service:1.0-snapshot
          # imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: "DB_CONNECTION"
              value: "host=postgres-user-cluster-ip-service user=postgres password=123456 dbname=postgres port=5432"
            - name: "DB_CONNECTION_STS"
              value: "host=postgres-sts-cluster-ip-service user=postgres password=123456 dbname=postgres port=5432"
            - name: "GRPC_STS"
              value: "sts-service-cluster-ip-service:50051"
