version: '3'

networks:
  investing-network:
    driver: bridge

services:
  postgres-user:
    image: 'postgres:13.1-alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./docker/postgres-data-user:/var/lib/postgresql/data
    ports:
      - 5432:5432    
    networks:
      - investing-network
  
  postgres-sts:
    image: 'postgres:13.1-alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./docker/postgres-data-sts:/var/lib/postgresql/data
    ports:
      - 5433:5432    
    networks:
      - investing-network

  mongo-ibovespa-assets:
    build: 
      dockerfile: Dockerfile.mongodb
      context: ./backend/scrapers/ibovespa-assets
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=ibovespa_assets
    ports:
      - 27017:27017
    networks:
      - investing-network
    volumes:
      - ./docker/mongo-data-ibovespa-assets:/data/db

  mongo-currency:
    build: 
      dockerfile: Dockerfile.mongodb
      context: ./backend/scrapers/currency
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=currency
    ports:
      - 27018:27017
    networks:
      - investing-network
    volumes:
      - ./docker/mongo-data-currency:/data/db

  mongo-selic:
    build: 
      dockerfile: Dockerfile.mongodb
      context: ./backend/scrapers/selic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=selic
    ports:
      - 27019:27017
    networks:
      - investing-network
    volumes:
      - ./docker/mongo-data-selic:/data/db

  sts-service:
    build: 
      dockerfile: Dockerfile
      context: ./backend/sts-service
    environment:
      - DB_CONNECTION=host=postgres-sts user=postgres password=123456 dbname=postgres port=5432
    ports:
      - 8089:8080    
      - 50051:50051
    networks:
      - investing-network
    volumes: 
      - ./backend/sts-service:/app
    depends_on: 
      - postgres-sts

  user-service:
    build: 
      dockerfile: Dockerfile
      context: ./backend/user-service
    environment:
      - DB_CONNECTION=host=postgres-user user=postgres password=123456 dbname=postgres port=5432
      - DB_CONNECTION_STS=host=postgres-sts user=postgres password=123456 dbname=postgres port=5432
      - GRPC_STS=sts-service:50051
    ports:
      - 8081:8081    
    networks:
      - investing-network
    volumes: 
      - ./backend/user-service:/app
    depends_on: 
      - postgres-user
      - sts-service

  scraper-ibovespa-assets:
    build: 
      dockerfile: Dockerfile.api
      context: ./backend/scrapers/ibovespa-assets
    ports:
      - '8082:3000'
    networks:
      - investing-network
    volumes: 
      - ./backend/scrapers/ibovespa-assets:/app
    depends_on: 
      - mongo-ibovespa-assets

  scraper-currency:
    build: 
      dockerfile: Dockerfile.api
      context: ./backend/scrapers/currency
    ports:
      - '8083:3000'
    networks:
      - investing-network
    volumes: 
      - ./backend/scrapers/currency:/app
    depends_on: 
      - mongo-currency

  scraper-selic:
    build: 
      dockerfile: Dockerfile.api
      context: ./backend/scrapers/selic
    ports:
      - '8084:3000'
    networks:
      - investing-network
    volumes: 
      - ./backend/scrapers/selic:/app
    depends_on: 
      - mongo-ibovespa-assets

  frontend:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./frontend/app
    environment:
      - VUE_APP_API_URL=http://localhost:80/api/
    ports:
      - '8080:8080'
    networks:
      - investing-network
    volumes: 
      - /app/node_modules
      - ./frontend/app:/app
    depends_on: 
      - user-service

  nginx:
    image: nginx:1.19.6
    restart: always    
    ports: 
      - 80:80
      - 443:443
    networks:
      - investing-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sts-service
      - user-service
      - scraper-ibovespa-assets
      - scraper-currency
      - scraper-selic
      - frontend
      